//! Profiling zones and callers (names only, no profiler integration yet).

#[derive(Copy, Clone, Debug)]
pub enum Zones {
    FlashAttentionFlashAttention,
    FlashAttentionInclusive,
    FlashAttentionRmsNormAndPositionalEncoding,
    FlashAttentionSingleFlashAttention,
    FlashAttentionTileFlashAttention,
    FlashAttentionTileFlashAttention4,
    FlashAttentionTransposeQ,
    GenActivation,
    GenActivationFused,
    GenAttention,
    GenAttentionComputeQKV,
    GenAttentionDotSoftmaxWeightedSumInclusive,
    GenAttentionDotSoftmaxWeightedSumPar,
    GenAttentionQDotK,
    GenAttentionSumHeads,
    GenEmbed,
    GenEmbeddingMatmul,
    GenFFW,
    GenSampleTop1,
    GenSampleTopK,
    MMDecompressA,
    MMDispatch,
    MMMatMul,
    MmntK,
    MmntMtK,
    MmntMt,
    MMNT,
    MMTwoMatMul,
    OpsAddFrom,
    OpsLogitsSoftCap,
    OpsMulByConstTo,
    OpsRmsNorm,
    OpsRmsNormInplace,
    OpsRmsNormMul,
    OpsRope,
    OpsRopeAndMulBy,
    OpsSoftmax,
    StartupWeightsReadAllToBF16,
    StartupWeightsReadBatches,
}

pub fn zone_name(zone: Zones) -> &'static str {
    match zone {
        Zones::FlashAttentionFlashAttention => "FlashAttention.FlashAttention",
        Zones::FlashAttentionInclusive => "FlashAttention.Inclusive",
        Zones::FlashAttentionRmsNormAndPositionalEncoding => {
            "FlashAttention.RMSNormAndPositionalEncoding"
        }
        Zones::FlashAttentionSingleFlashAttention => "FlashAttention.SingleFlashAttention",
        Zones::FlashAttentionTileFlashAttention => "FlashAttention.TileFlashAttention",
        Zones::FlashAttentionTileFlashAttention4 => "FlashAttention.TileFlashAttention4",
        Zones::FlashAttentionTransposeQ => "FlashAttention.TransposeQ",
        Zones::GenActivation => "Gen.Activation",
        Zones::GenActivationFused => "Gen.ActivationFused",
        Zones::GenAttention => "Gen.Attention",
        Zones::GenAttentionComputeQKV => "Gen.Attention.ComputeQKV",
        Zones::GenAttentionDotSoftmaxWeightedSumInclusive => {
            "Gen.Attention.DotSoftmaxWeightedSumInclusive"
        }
        Zones::GenAttentionDotSoftmaxWeightedSumPar => "Gen.Attention.DotSoftmaxWeightedSum.par",
        Zones::GenAttentionQDotK => "Gen.Attention.QDotK",
        Zones::GenAttentionSumHeads => "Gen.Attention.SumHeads",
        Zones::GenEmbed => "Gen.Embed",
        Zones::GenEmbeddingMatmul => "Gen.EmbeddingMatmul",
        Zones::GenFFW => "Gen.FFW",
        Zones::GenSampleTop1 => "Gen.SampleTop1",
        Zones::GenSampleTopK => "Gen.SampleTopK",
        Zones::MMDecompressA => "MM.DecompressA",
        Zones::MMDispatch => "MM.Dispatch",
        Zones::MMMatMul => "MM.MatMul",
        Zones::MmntK => "MM.NT_K",
        Zones::MmntMtK => "MM.NT_MT_K",
        Zones::MmntMt => "MM.NT_MT",
        Zones::MMNT => "MM.NT",
        Zones::MMTwoMatMul => "MM.TwoMatMul",
        Zones::OpsAddFrom => "Ops.AddFrom",
        Zones::OpsLogitsSoftCap => "Ops.LogitsSoftCap",
        Zones::OpsMulByConstTo => "Ops.MulByConstTo",
        Zones::OpsRmsNorm => "Ops.RMSNorm",
        Zones::OpsRmsNormInplace => "Ops.RMSNormInplace",
        Zones::OpsRmsNormMul => "Ops.RMSNormMul",
        Zones::OpsRope => "Ops.Rope",
        Zones::OpsRopeAndMulBy => "Ops.RopeAndMulBy",
        Zones::OpsSoftmax => "Ops.Softmax",
        Zones::StartupWeightsReadAllToBF16 => "Startup.Weights.ReadAllToBF16",
        Zones::StartupWeightsReadBatches => "Startup.Weights.ReadBatches",
    }
}

#[derive(Copy, Clone, Debug)]
pub enum Callers {
    ActivationBatched,
    AllocateAndBindAll,
    AttComputeQKV,
    AttDotSoftmaxWeightedSum,
    BlobWriter,
    Compress,
    FixupWeights,
    FlashAttention,
    FlashRMSNormAndPositionalEncoding,
    FlashTransposeQ,
    MMClusterForMC,
    MMClusterForMCNC,
    MMClusterForN,
    MMHierForMC,
    MMHierForMCNC,
    MMHierForN,
    OpsAddFromBatched,
    OpsMaybeLogitsSoftCapBatched,
    OpsRMSNormBatched,
    OpsRMSNormInplaceBatched,
    ReadAllToBF16,
    ReadBatches,
    SampleAndStream,
    Test,
    TunePool,
    VitDotSoftmax1,
    VitDotSoftmax2,
    VitDotSoftmax3,
    VitDotSoftmax4,
}

pub fn caller_name(caller: Callers) -> &'static str {
    match caller {
        Callers::ActivationBatched => "ActivationBatched",
        Callers::AllocateAndBindAll => "AllocateAndBindAll",
        Callers::AttComputeQKV => "Att.ComputeQKV",
        Callers::AttDotSoftmaxWeightedSum => "Att.DotSoftmaxWeightedSum",
        Callers::BlobWriter => "BlobWriter",
        Callers::Compress => "Compress",
        Callers::FixupWeights => "FixupWeights",
        Callers::FlashAttention => "FlashAttention",
        Callers::FlashRMSNormAndPositionalEncoding => "Flash.RMSNormAndPositionalEncoding",
        Callers::FlashTransposeQ => "Flash.TransposeQ",
        Callers::MMClusterForMC => "MM.ClusterForMC",
        Callers::MMClusterForMCNC => "MM.ClusterForMCNC",
        Callers::MMClusterForN => "MM.ClusterForN",
        Callers::MMHierForMC => "MM.HierForMC",
        Callers::MMHierForMCNC => "MM.HierForMCNC",
        Callers::MMHierForN => "MM.HierForN",
        Callers::OpsAddFromBatched => "Ops.AddFromBatched",
        Callers::OpsMaybeLogitsSoftCapBatched => "Ops.MaybeLogitsSoftCapBatched",
        Callers::OpsRMSNormBatched => "Ops.RMSNormBatched",
        Callers::OpsRMSNormInplaceBatched => "Ops.RMSNormInplaceBatched",
        Callers::ReadAllToBF16 => "ReadAllToBF16",
        Callers::ReadBatches => "ReadBatches",
        Callers::SampleAndStream => "SampleAndStream",
        Callers::Test => "Test-only!",
        Callers::TunePool => "TunePool",
        Callers::VitDotSoftmax1 => "Vit.DotSoftmax1",
        Callers::VitDotSoftmax2 => "Vit.DotSoftmax2",
        Callers::VitDotSoftmax3 => "Vit.DotSoftmax3",
        Callers::VitDotSoftmax4 => "Vit.DotSoftmax4",
    }
}
